### ISSUE TITLE
Moving Platform with Keyboard Keys

### ISSUE THREAD

**Issue by agrajagrawal** [untitled-team-101/Bricks-Breaker#3]
Currently we can move the platform "that releases ball" with mouse only,
Game will look more cool if we allow to movement with keyboard left right keys!

I want to work upon this, Please do assign me this issue!

**Comment by KarthikS373** [comment]
I would like to work on this too. Is is possible to assign me over this issue please

**Comment by grawish** [comment]
@KarthikS373 any updates?
